[package]
name = "lru-cache"
version = "1.0.0"
description = "A Least Recently Used Cache implementation"
repository = "https://github.com/NatLabs/lru-cache"
keywords = ["map", "linked-list", "fixed-size"]
license = "MIT"

[dependencies]
"core@1.0.0" = "1.0.0"
"map@9.0.1" = "9.0.1"
'linked-list@0.1.0' = "0.1.0"
'buffer@0.1.0' = "0.1.0"

[dev-dependencies]
test = "2.1.1"
bench = "1.0.0"
fuzz = "1.0.0"

[toolchain]
wasmtime = "33.0.1"
moc = "0.16.2"
